name: Deploy to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x-preview'
        
    - name: Restore dependencies
      run: dotnet restore PerfumeMonitor.Web/PerfumeMonitor.Web.csproj
      
    - name: Build
      run: dotnet build PerfumeMonitor.Web/PerfumeMonitor.Web.csproj --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish PerfumeMonitor.Web/PerfumeMonitor.Web.csproj --configuration Release --no-build --output ./publish
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish 